datasets:
  arch.business.products:
    source: >
      (
                $components := $.components;
                {
                  "products" : 
                    $.products.$spread().{
                          "id": $keys()[0],
                          "product": $.*
                        }.
                        (
                            $prod_id := id;
                            $merge([product, {
                                "id": id,
                                "list": $append([], $components.$spread().{
                                        "id": $keys()[0],
                                        "component": $.*
                                    }.
                                    (   
                                        $id := id;
                                        $title := component.title;
                                        $exists(component.products) ?

                                            component.products.(
                                                $ = $prod_id ? (
                                                    {
                                                        "id": $id,
                                                        "title": $title
                                                    }
                                                )
                                            )

                                    ))
                            }])
                    ),
                  "capabilities": 
                      $.capabilities.$spread().{
                                          "id": $keys()[0],
                                          "capability": $.*
                                      }.
                                      (
                                          $cap_id := id;
                                          capability.type = "group" ? (
                                              $merge([capability, {
                                                  "id": id
                                              }])
                                          ) :
                                          (
                                              $merge([capability, {
                                                  "id": id,
                                                  "list": $append([], $components.$spread().{
                                                        "id": $keys()[0],
                                                        "component": $.*
                                                    }.
                                                    (   
                                                        $id := id;
                                                        $title := component.title;
                                                        $exists(component.capabilities) ?
                                                            component.capabilities.(
                                                                $.id = $cap_id ? (
                                                                    {
                                                                        "id": $id,
                                                                        "title": $title,
                                                                        "level" : $.level
                                                                    }
                                                                )
                                                            )

                                                     ))
                                  }])
                              )
                          )
                  }
      )
